const jobs={
    "job1": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job2": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job3": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job4": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job5": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job6": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job7": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job8": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job9": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
    "job10": {
        "Company": "Apple Inc.",
        "Role": "Web Developer",
        "Location": "Silicon Valley",
        "Time": "Full-time",
        "Salary": "Upto $2M",
        "Status": "awaiting",
        "Description": "Basic Knowledge in Web Development, ",
    },
}